### ISSUE TITLE
超时判定bug

### ISSUE THREAD

**Issue by equation314** [sxyzccr/CCR-Plus#16]
当被测程序所用的系统 CPU 时间较多时，虽然最后用户 CPU 时间没超时，但如果总用时大于 时限+10ms，还是会被计时器判定为超时。

**Comment by zhzh2001** [comment]
好像将basejudger.cpp中的QElapsedTimer改用ctime后可以解决这个问题。
```c++
time_t t=clock();
for (;(double)(clock()-t)/CLOCKS_PER_SEC*1000 <= ms;)
    {
        //do something
        QCoreApplication::processEvents();
        QThread::msleep(10);
    }
```

**Comment by equation314** [comment]
已在 #17 中修复。

**Comment by zhzh2001** [comment]
然而这个问题好像并没有修复，只是从**超时**变成了**进程被阻塞**而已。在NOI Linux和Windows 10下均测试过。而且在Windows下，本应该判为超时的也变成进程被阻塞。

**Comment by equation314** [comment]
超时是指进程 CPU 时间超过时间限制，和总运行时间是不一样的。
