### ISSUE TITLE
win7环境变量配置后测试216怎么破

### ISSUE THREAD

**Issue by tabbbbbb** [sxyzccr/CCR-Plus#37]
win7环境变量配置如下：
C:\Program Files\Dev-Cpp\MinGW64\bin
但是测试提示：无法运行程序：216
这个如何解决？

**Comment by equation314** [comment]
错误216的意思是：
> 该版本的 %1 与您运行的 Windows 版本不兼容。请查看计算机的系统信息，了解是否需要 x86 (32 位)或 x64 (64 位)版本的程序，然后联系软件发布者。

可能是您的系统是32位，无法运行64位程序。
