### ISSUE TITLE
error: use of undeclared identifier 'qSort'

### ISSUE THREAD

**Issue by Sheng-Horizon** [sxyzccr/CCR-Plus#45]
我试图用linux方法在macOS上用qmake编译，出现了上述问题

**Comment by equation314** [comment]
改为使用 `std::sort`

**Comment by equation314** [comment]
目前尚不支持在macOS下或使用高版本Qt进行编译。

下面提供几个以上错误的修复思路：
1. 去掉 common/problem.h:7 的 `QStringList`
2. common/problem.h 中加入 `#include <QRegExp>`

**Comment by Sheng-Horizon** [comment]
重装了qt，似乎好了
